added option struct
dims/maintainers pull request #16
Opened 2022-03-04 07:22 UTC by AvineshTripathi

#12 
replaced the global variables with a struct 
cc @MadhavJivrajani

2022-03-04 07:42 UTC, palnabarun requested changes

2022-03-04 07:42 UTC, palnabarun commented on cmd/prune.go
> +}
I think it's better to use plural for the name here. `option` -> `options`.

Also, can you please run `go fmt` on the code? Tiny nit: there's an extra new line and the type indentation seems to be off.

2022-03-04 10:18 UTC, AvineshTripathi commented
Did a rebase with changes asked let me know if I did incorrectly

2022-06-10 09:51 UTC, MadhavJivrajani commented
/lgtm
/approve
Apologies for the delay!

2022-06-10 09:53 UTC, merged